version: "3.9"

services:
  devopsdb:
    image: kvreddy9120/newcicd:db
    deploy:
      replicas: 1
    networks:
      - mynetwork

  application:
    image: kvreddy9120/newcicd:app
    ports:
      - "1111:8080"
    deploy:
      replicas: 3
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
